version: '3.4'
#add service build to container with docker compose
services:
  nodejs:
    image: caseyupload/cpe-upload
    build:
      context: .
      dockerfile: ./Dockerfile
    #fix .env your project
    environment:
      NODE_ENV: production
      # pirvate config your project
      #this nginx reverse proxy and config load balancer
  nginx:
    image: nginx:latest
    volumes:
      #- ./:/your/project/root/directory/path
      - ./conf.d:/etc/nginx/conf.d
      
      - /home/docker-service/certbot/www:/var/www/certbot
      #- /your/project/root/public/directory/path:/var/www/certbot

      - /etc/letsencrypt/:/etc/nginx/
      #- /etc/letsencrypt/ssl/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      #- /etc/letsencrypt/ssl/privkey.pem:/etc/nginx/ssl/privkey.pem
    restart: always
    #traget service
    depends_on:
      - nodejs
    #port to public
    ports:
      - "${SSL_PORT}:443"
      - "${HTTP_PORT}:80"
   # command docker when you want run by scale
   # docker-compose up --scale your_service=3 -d --build